### ISSUE TITLE
Wonky padding in header on mobile/ tablet breakpoints

### ISSUE THREAD

**Issue by akmadian** [cc-archive/vocabulary-legacy#241]
## Describe the bug

After design sprint 1 (#723) was merged, the header now has some wonky padding in mobile breakpoints
- The Search logo is pushed too far to the right
- The hamburger is not pushed off of the right side of the screen

## To Reproduce

1. Go to ccsearch-dev.creativecommons.org
2. Use browser to simulate a mobile/ tablet screen
3. See error

## Screenshots

![header0](https://user-images.githubusercontent.com/28791774/77197067-be1be700-6aa1-11ea-9429-697616c00be6.PNG)

## Desktop (please complete the following information)
 - OS: Win 10 Pro 1909
 - Browser: Firefox Dev. Ed. 75.0

**Comment by oneshasappleton** [comment]
I would like to work on this seeing that no one else has been, please. Thanks in advance.

**Comment by oneshasappleton** [comment]
thank you

**Comment by Tanuj22** [comment]
@dhruvkb I think this issue has been fixed and can be closed.  
![Capture](https://user-images.githubusercontent.com/42486853/80527412-f3292c80-89b1-11ea-89ac-7d1936bc696b.JPG)

**Comment by dhruvkb** [comment]
@akmadian can you verify https://github.com/creativecommons/vocabulary/issues/241#issuecomment-620800448?

**Comment by Dishebh** [comment]
@dhruvkb @akmadian Is the issue still up for grabs? If yes, can I work on it?

**Comment by dhruvkb** [comment]
Unassigned because of inactivity. Still waiting for @akmadian to verify https://github.com/creativecommons/vocabulary/issues/241#issuecomment-620800448.

**Comment by kgodey** [comment]
This is not an issue any more.
